In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO

import numpy as np

#Fin Data Sources
import yfinance as yf
import pandas_datareader as pdr

#Data viz
import plotly.graph_objs as go
import plotly.express as px

import time
from datetime import date
import matplotlib.pyplot as plt

In [65]:
pip install gdown pyarrow

Collecting gdown
  Downloading gdown-6.4.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pyarrow in c:\users\adminj\anaconda3\lib\site-packages (21.0.0)
Requirement already satisfied: beautifulsoup4 in c:\users\adminj\anaconda3\lib\site-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in c:\users\adminj\anaconda3\lib\site-packages (from gdown) (3.20.0)
Requirement already satisfied: requests[socks] in c:\users\adminj\anaconda3\lib\site-packages (from gdown) (2.32.5)
Requirement already satisfied: tqdm in c:\users\adminj\anaconda3\lib\site-packages (from gdown) (4.67.1)
Requirement already satisfied: urllib3 in c:\users\adminj\anaconda3\lib\site-packages (from gdown) (2.5.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\adminj\anaconda3\lib\site-packages (from beautifulsoup4->gdown) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\adminj\anaconda3\lib\site-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\adminj\anaconda3\lib\site-packages (from requests[socks]->gdown) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\adminj\anaconda3\lib\site-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\adminj\anaconda3\lib\site-packages (from requests[socks]->gdown) (2025.11.12)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\adminj\anaconda3\lib\site-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: colorama in c:\users\adminj\anaconda3\lib\site-packages (from tqdm->gdown) (0.4.6)
Downloading gdown-6.4.1-py3-none-any.whl (50 kB)
Installing collected packages: gdown
Successfully installed gdown-6.4.1
Note: you may need to restart the kernel to use updated packages.

In [66]:
import gdown
file_id = "1grCTCzMZKY5sJRtdbLVCXg8JXA8VPyg-"
gdown.download(f"https://drive.google.com/uc?id={file_id}", "data.parquet", quiet=False)
df_parquet = pd.read_parquet("data.parquet", engine="pyarrow")

Downloading...
From (original): https://drive.google.com/uc?id=1grCTCzMZKY5sJRtdbLVCXg8JXA8VPyg-
From (redirected): https://drive.google.com/uc?id=1grCTCzMZKY5sJRtdbLVCXg8JXA8VPyg-&confirm=t&uuid=8703b7ef-0d02-436b-9ffa-0ae10508d41b
To: C:\Users\AdminJ\data.parquet
100%|██████████| 130M/130M [00:15<00:00, 8.17MB/s]

In [73]:
df_parquet.columns

Index(['Open', 'High', 'Low', 'Close_x', 'Volume', 'Dividends', 'Stock Splits',
       'Ticker', 'Year', 'Month',
       ...
       'growth_brent_oil_7d', 'growth_brent_oil_30d', 'growth_brent_oil_90d',
       'growth_brent_oil_365d', 'growth_btc_usd_1d', 'growth_btc_usd_3d',
       'growth_btc_usd_7d', 'growth_btc_usd_30d', 'growth_btc_usd_90d',
       'growth_btc_usd_365d'],
      dtype='object', length=203)

In [80]:
df_parquet["rsi"]

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
          ...
5686    68.312972
5687    67.123448
5688    67.563912
5689    68.218963
5690    69.670158
Name: rsi, Length: 229932, dtype: float64

In [88]:
df_parquet

,Open,High,Low,Close_x,Volume,Dividends,Stock Splits,Ticker,Year,Month,...,growth_brent_oil_7d,growth_brent_oil_30d,growth_brent_oil_90d,growth_brent_oil_365d,growth_btc_usd_1d,growth_btc_usd_3d,growth_btc_usd_7d,growth_btc_usd_30d,growth_btc_usd_90d,growth_btc_usd_365d
0,0.054277,0.062259,0.054277,0.059598,1.031789e+09,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.059598,0.062791,0.059598,0.061726,3.081600e+08,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.061726,0.063323,0.061726,0.062791,1.331712e+08,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.062791,0.063323,0.060662,0.061194,6.776640e+07,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.061194,0.061726,0.059598,0.060130,4.789440e+07,0.0,0.0,MSFT,1986,1986-03-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5686,3615.800049,3672.500000,3608.399902,3648.699951,1.678934e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,NaN,NaN,NaN,NaN,1.003714,1.020064,1.036306,1.156301,1.233323,1.597248
5687,3648.699951,3665.000000,3603.000000,3640.000000,2.013954e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,0.993181,0.989654,0.781299,0.842957,0.995927,1.011165,1.020634,1.162549,1.292217,1.570651
5688,3660.000000,3663.000000,3620.000000,3646.300049,1.293244e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,0.992203,1.000308,0.798376,0.886128,0.989061,0.988691,0.982898,1.135015,1.272691,1.578452
5689,3663.899902,3668.899902,3618.000000,3655.300049,1.972248e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,0.978792,0.991959,0.794034,0.863857,0.979958,0.965291,0.945990,1.120454,1.252080,1.563254
5690,3655.300049,3695.300049,3654.500000,3675.100098,2.571304e+06,0.0,0.0,LT.NS,2025,2025-05-01,...,0.958856,0.952012,0.790642,0.818300,0.984446,0.954162,0.969342,1.103933,1.208837,1.521226

In [83]:
rsi_threshold = 30

In [85]:
oversold_filt = df_parquet["rsi"] < rsi_threshold

In [86]:
df_oversold = df_parquet[oversold_filt].copy()

In [87]:
df_oversold

,Open,High,Low,Close_x,Volume,Dividends,Stock Splits,Ticker,Year,Month,...,growth_brent_oil_7d,growth_brent_oil_30d,growth_brent_oil_90d,growth_brent_oil_365d,growth_btc_usd_1d,growth_btc_usd_3d,growth_btc_usd_7d,growth_btc_usd_30d,growth_btc_usd_90d,growth_btc_usd_365d
81,0.062259,0.062259,0.059066,0.059598,46137600.0,0.0,0.0,MSFT,1986,1986-07-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,0.059598,0.060130,0.055341,0.058001,46886400.0,0.0,0.0,MSFT,1986,1986-07-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,0.058533,0.058533,0.055873,0.057469,18316800.0,0.0,0.0,MSFT,1986,1986-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,0.206996,0.206996,0.190500,0.192096,197078400.0,0.0,0.0,MSFT,1987,1987-07-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,0.261804,0.270318,0.191564,0.192628,146880000.0,0.0,0.0,MSFT,1987,1987-10-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4938,1472.086837,1515.287317,1445.146685,1476.416504,4328846.0,0.0,0.0,LT.NS,2022,2022-05-01,...,1.012802,1.033732,1.394375,2.352383,1.008102,0.943919,0.812496,0.711329,0.693182,0.589005
4939,1491.330009,1508.167606,1481.179297,1484.498779,1775914.0,0.0,0.0,LT.NS,2022,2022-05-01,...,1.030117,1.094358,1.413861,2.367668,0.953931,1.019800,0.985674,0.738733,0.669945,0.642821
5428,3286.911956,3350.660834,3241.171420,3249.902832,12120574.0,0.0,0.0,LT.NS,2024,2024-05-01,...,0.954701,0.974329,1.088785,1.002989,1.030431,0.998227,1.066412,0.911930,1.337300,2.282620
5429,3256.005062,3280.363389,3209.371641,3245.934082,4132191.0,0.0,0.0,LT.NS,2024,2024-05-01,...,0.992210,0.946388,1.090921,0.995192,0.964200,0.975262,0.966655,0.861235,1.272580,2.251519
5544,3425.000000,3435.000000,3315.050049,3326.399902,3236774.0,0.0,0.0,LT.NS,2024,2024-10-01,...,1.024656,1.062003,0.891246,1.015218,0.977720,0.989326,0.974037,1.055418,0.982733,1.951082

In [97]:
date_filt = ((df_oversold["Date"] >= "2000-01-01") & (df_oversold["Date"] <= "2025-06-01"))

In [98]:
df_oversold["Date"].dtype

dtype('<M8[ns]')

In [103]:
filtered_df = df_oversold[date_filt].copy()

In [104]:
filtered_df

,Open,High,Low,Close_x,Volume,Dividends,Stock Splits,Ticker,Year,Month,...,growth_brent_oil_7d,growth_brent_oil_30d,growth_brent_oil_90d,growth_brent_oil_365d,growth_btc_usd_1d,growth_btc_usd_3d,growth_btc_usd_7d,growth_btc_usd_30d,growth_btc_usd_90d,growth_btc_usd_365d
3562,24.252026,24.366965,22.451323,22.719513,151217800.0,0.0,0.0,MSFT,2000,2000-04-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3567,20.612310,20.842187,19.922679,20.420746,313645800.0,0.0,0.0,MSFT,2000,2000-04-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3667,21.052906,21.072063,20.133398,20.171711,78503000.0,0.0,0.0,MSFT,2000,2000-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3668,20.056772,20.114241,19.405453,19.673643,99915200.0,0.0,0.0,MSFT,2000,2000-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3669,19.692798,19.807736,19.060636,19.309669,69037800.0,0.0,0.0,MSFT,2000,2000-09-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4938,1472.086837,1515.287317,1445.146685,1476.416504,4328846.0,0.0,0.0,LT.NS,2022,2022-05-01,...,1.012802,1.033732,1.394375,2.352383,1.008102,0.943919,0.812496,0.711329,0.693182,0.589005
4939,1491.330009,1508.167606,1481.179297,1484.498779,1775914.0,0.0,0.0,LT.NS,2022,2022-05-01,...,1.030117,1.094358,1.413861,2.367668,0.953931,1.019800,0.985674,0.738733,0.669945,0.642821
5428,3286.911956,3350.660834,3241.171420,3249.902832,12120574.0,0.0,0.0,LT.NS,2024,2024-05-01,...,0.954701,0.974329,1.088785,1.002989,1.030431,0.998227,1.066412,0.911930,1.337300,2.282620
5429,3256.005062,3280.363389,3209.371641,3245.934082,4132191.0,0.0,0.0,LT.NS,2024,2024-05-01,...,0.992210,0.946388,1.090921,0.995192,0.964200,0.975262,0.966655,0.861235,1.272580,2.251519
5544,3425.000000,3435.000000,3315.050049,3326.399902,3236774.0,0.0,0.0,LT.NS,2024,2024-10-01,...,1.024656,1.062003,0.891246,1.015218,0.977720,0.989326,0.974037,1.055418,0.982733,1.951082

In [105]:
filtered_df = filtered_df.dropna(subset=["growth_future_30d"])

In [106]:
filtered_df["net_income"] = (1000 * (filtered_df["growth_future_30d"] - 1) )

In [107]:
net_income = filtered_df["net_income"].sum()

In [108]:
net_income

np.float64(65805.58960747934)

In [109]:
total_invested = len(filtered_df) * 1000

In [110]:
total_invested

5206000